# Available ruby versions: http://rubies.travis-ci.org/

language: ruby

os:
  - linux
  # - osx

rvm:
  - "2.0.0-p0"
  - "2.0.0-p195"
  - "2.0.0-p247"
  - "2.0.0-p353"
  - "2.0.0-p451"
  - "2.0.0-p481"
  - "2.0.0-p576"
  - "2.0.0-p598"
  - "2.0.0-p647"
  - "2.0.0-p648"

  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
  - "2.1.3"
  - "2.1.4"
  - "2.1.5"
  - "2.1.6"
  - "2.1.7"
  - "2.1.8"
  - "2.1.9"
  - "2.1.10"

  - "2.2.0"
  - "2.2.1"
  - "2.2.2"
  - "2.2.3"
  - "2.2.4"
  - "2.2.5"
  - "2.2.6"

  - "2.3.0"
  - "2.3.1"
  - "2.3.2"
  - "2.3.3"

  - "2.4.0"

  - "ruby-head"

  - "jruby-9.0.5.0"
  - "jruby-9.1.5.0"
  - "jruby-head"

script:
  bundle exec rake test

branches:
  except:
    - "readme-edits"

before_install:
  - gem update --system
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

# Travis OS X support is pretty janky. These are some hacks to include tests
# only on versions that actually work.
# (last tested: 2016-11)
matrix:
  # exclude: {}
  # include: {}

  allow_failures: []
    # - rvm: 'ruby-head'

  # return results as soon as mandatory versions are done
  fast_finish: true

sudo: false


# Use Java 8 for jruby to fix some Java 7 bugs.
addons:
  apt:
    packages:
      - oracle-java8-set-default
