language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
gemfile:
  - "Gemfile"
  - "gemfiles/Gemfile.min"
branches:
  except:
    - "readme-edits"

# For expediency, let us assume that anyone running the latest Ruby is not
# running anything but the latest gems. :-)
matrix:
  exclude:
    - rvm: "2.0.0"
      gemfile: "gemfiles/Gemfile.min"
