# Available ruby versions: http://rubies.travis-ci.org/

language: ruby

os:
  - linux
  - osx

rvm:
  - "2.0.0"
  - "2.1" # latest 2.1.x
  - "2.2.5" # TODO: switch to "2.2" once it works for OS X
  - "2.3.1" # TODO: switch to "2.3" once travis fixes it
  - "ruby-head"
  - "jruby-9.0.5.0"
  - "jruby-9.1.5.0"
  - "jruby-head"

script:
  bundle exec rake test

branches:
  except:
    - "readme-edits"

before_install:
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

# Travis OS X support is pretty janky. These are some hacks to include tests
# only on versions that actually work.
# (last tested: 2016-10)
matrix:
  # exclude: {}
  # include: {}

  allow_failures:

    # bundle fails on ruby 2.4 due to rdoc dependency on json
    # https://github.com/flori/json/issues/303
    - rvm: 'ruby-head'

    # jruby 9.1.x.x fails tests due to bug below
    - os: osx
      rvm: 'jruby-head'
    - os: linux
      rvm: 'jruby-head'

    # jruby 9.1.x.x fails tests due to jruby bug
    # https://github.com/jruby/jruby/issues/4217
    - os: osx
      rvm: 'jruby-9.1.5.0'
    - os: linux
      rvm: 'jruby-9.1.5.0'

  # return results as soon as mandatory versions are done
  fast_finish: true

sudo: false
