language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "jruby-19mode"
script:
  bundle exec rake test
branches:
  except:
    - "readme-edits"
matrix:
  allow_failures:
    rvm: "2.1.0"
  fast_finish: true
